qom-obj-y = object.o container.o qom-qobject.o
qom-obj-y += object_interfaces.o

common-obj-y = cpu.o

remote-pci-obj-$(CONFIG_MPQEMU) += object.o qom-qobject.o container.o
remote-pci-obj-$(CONFIG_MPQEMU) += object_interfaces.o
remote-pci-obj-$(CONFIG_MPQEMU) += cpu.o
